name: guitar_chord_library
description: A perfect simple chord library for guitar and ukulele. Both flat and sharp note usage are supported.
version: 0.0.5
homepage: https://github.com/ygnCybernoob/guitar_chord_library

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
